{
 "title": "Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": "SELECT \"name\" FROM service"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Service Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM service WHERE (\"name\" = '$Service')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "x11-common" }
     ]
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"n_cpus\" FROM \"cpu\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"n_threads\" FROM cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100 - \"usage_idle\" FROM cpu ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"used_percent\" FROM \"mem\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cpu",
     "query": "SELECT  100 - \"usage_idle\"  FROM \"cpu\" ",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       { "params": [ "/100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT total FROM processes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Idle Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT idle FROM processes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blocked Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT blocked FROM processes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"used\"  / 1000000 FROM \"mem\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processes by Most CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM cpu \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processes by Most Mem Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM mem \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}